name: Déployer le site Hugo sur GitHub Pages

on:
  push:
    branches: [ main ]  # remplace "main" si ta branche principale s'appelle autrement
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4
        with:
          submodules: true  # requis si tu utilises PaperMod comme sous-module Git

      - name: Installer Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Construire le site Hugo
        run: hugo --minify

      - name: Uploader le site (artefact)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Déployer vers GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
